### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by nonamejan** [benmotyka/crypto-checker#1]
I get this error when using `npm run dev`

![grafik](https://user-images.githubusercontent.com/113781755/211200693-ca300dc8-12ad-4c62-b197-f94bdcc4be0d.png)

**Comment by benmotyka** [comment]
Hi @nonamejan, can you please double check if you are in the correct directory (the project that you just cloned). I will update README soon, basically after you clone the project you need to enter it (`cd discord-payment-bot`), install npm dependencies (`npm install`), create .env file, start a local database (`docker-compose up`) and then finally run the app with npm run dev (provided that you are in the correct directory).

**Comment by benmotyka** [comment]
Fixed README
